### ISSUE TITLE
[Roadmap] Big refactoring of this repository

### ISSUE THREAD

**Issue by MouriNaruto** [lvgl/lv_port_pc_visual_studio#53]
In order to better maintain LVGL for Windows Visual Studio port, I have planned to do a big refactoring for this repository. I think it may be the biggest refactoring since I become the maintainer of this repository. Here is the list of things I need to do.

- [x] Merge the features from [lv_port_windows](https://github.com/lvgl/lv_port_windows) for improving the maintain work and simplify the LVGL users choice.
  - [x]  Create a project called LvglWindowsDesktopApplication project in this repository for migrating the LVGL.Windows.Desktop project from [lv_port_windows](https://github.com/lvgl/lv_port_windows).
  - [x] Add several features for [win32drv](https://github.com/lvgl/lv_drivers/tree/master/win32drv).
    - [x] Add the "Application Mode" for using LVGL to develop Windows desktop applications.
    - [x] Add window resizing support for "Application Mode".
    - [x] Add Per Monitor DPI Awareness V1 (Windows 10, but before Build 14986) and V2 (Windows 10 Build 14986 and later) support for "Application Mode".
    - [x] Add Input Method Editors (IME) support for "Application Mode".
  - [ ] Add Windows GDI font engine backend to [LVGL main repository](https://github.com/lvgl/lvgl)
  - [x] Update the ReadMe document of [lv_port_windows](https://github.com/lvgl/lv_port_windows) for noticing user the repository will be archived and notify @kisvegabor.
- [x] Tidy the implementation of [LVGL.Simulator](https://github.com/lvgl/lv_port_win_visual_studio/tree/master/LVGL.Simulator).
  - [x] Rename LVGL.Simulator to LvglWindowsSimulator for resolving https://github.com/lvgl/lv_port_win_visual_studio/issues/42.
  - [x] ~~Create MSBuild shared item project for hosting the submodules~~ Create the MSBuild project generator for this repository for resolving https://github.com/lvgl/lv_port_win_visual_studio/issues/49.
 - [x] Improve the performance and fix bugs for [win32drv](https://github.com/lvgl/lv_drivers/tree/master/win32drv).
   - [x] Try to resolve https://github.com/lvgl/lv_port_win_visual_studio/issues/48. 
 - [x] Implement the win32drv vNext with the [new driver architecture](https://github.com/lvgl/lvgl/tree/arch/drivers)

Kenji Mouri

**Comment by kisvegabor** [comment]
Sounds like a good plan!

**Comment by MouriNaruto** [comment]
Finally, I have implemented the MSBuild project updater properly in https://github.com/lvgl/lv_port_win_visual_studio/blob/master/LvglMaintainerTools/LvglSubmoduleProjectFileGenerator/Program.cs. Users can change the files in lvgl and freetype filter in Visual Studio IDE freely and resolve the issue https://github.com/lvgl/lv_port_win_visual_studio/issues/49.

I can finally to push the progress for merging the features from [lv_port_windows](https://github.com/lvgl/lv_port_windows) for improving the maintain work and simplify the LVGL users choice.

Kenji Mouri

**Comment by kisvegabor** [comment]
> Users can change the files in lvgl and freetype filter in Visual Studio IDE freely and resolve the issue https://github.com/lvgl/lv_port_win_visual_studio/issues/49.

It's amazing, it was an issue for some of our customers a couple of times. 

> I can finally to push the progress for merging the features from [lv_port_windows](https://github.com/lvgl/lv_port_windows) for improving the maintain work and simplify the LVGL users choice.

It's also great!  Does it mean some parts can be added to LVGL master too? Or is it an other story?

**Comment by MouriNaruto** [comment]
@kisvegabor 

> Does it mean some parts can be added to LVGL master too? 

In sort of, yes. I want to provide a better implementation for LVGL, so I tangled quite a few things. It makes me reduce the something which I tangled.

For example, I want to provide a flexible and modular implementation for people, make people can integrate LVGL content (simulator mode or application mode) in other windows easily. I think it will make LVGL users happy because it can bring many possibilities. This is why I am tangled for implementing the new Windows backend. (I want to create a better design.)

Here are the things I want to provide in new Windows backend.

- LVGL content hosting support in windows which provides the HWND for interop with other UI frameworks like MFC, Qt, WinForms, WPF etc. (Maybe we can use that to implement the LVGL Designer for Visual Studio.)
- Multiple render backend support. In the current stage, I think I will only provide the Windows GDI backend. (But I hope I can provide the Direct2D backend in the future for reducing the overhead when Desktop Window Manager to composite the Window contents and have a good scaling quality for the simulator mode.)
- I also hope I can implement UI Automation support. It can make LVGL supports accessibility in Windows Vista and later. I have several friends who are blind, this is why I care about accessibly. Also, users can use that to do unit tests for LVGL content in Windows.

Kenji Mouri

**Comment by kisvegabor** [comment]
Sounds great! 👍

From the GitHub star count clearly the Windows port repos are the most popular ones, so I'm really happy that they will be even better 😊

**Comment by MouriNaruto** [comment]
@kisvegabor 

I hope this repository could be renamed to lv_port_pc_visual_studio.

Because one of my friends created the project which can build Linux projects managed by Visual Studio project file in the local Linux instance. Here is the repository: https://github.com/Chuyu-Team/MSBuildCppCrossToolset

![image](https://github.com/lvgl/lv_port_win_visual_studio/assets/10867563/a847323b-55cd-437d-862f-1e6210cdf8f6)

I will utilize this project to create a Visual Studio project which is for LVGL Linux Wayland application demo for showing more possibilities for users.

Kenji Mouri

**Comment by kisvegabor** [comment]
Woooow, it sounds amazing! Just let me when can I rename it :blush:

**Comment by MouriNaruto** [comment]
@kisvegabor 

> Woooow, it sounds amazing! Just let me when can I rename it 😊

It's time to rename now and I will commit these changes recently.

Kenji Mouri

**Comment by kisvegabor** [comment]
Done :slightly_smiling_face:

**Comment by MouriNaruto** [comment]
@kisvegabor 

Also, the https://github.com/lvgl/lv_port_windows repository can be archived now because I have updated the deprecated information.

I am working on the replacement implementation now and I can commit them to this repository today or tomorrow.

Kenji Mouri

**Comment by MouriNaruto** [comment]
Except for adding Windows GDI font engine backend. All related work has done by https://github.com/lvgl/lvgl/pull/5313.

Kenji Mouri
